stages:
  data_ingestion:
    cmd: src/pipeline/stage0_data_ingestion.py
    deps:
      - data/raw
      - src/pipeline/stage0_data_ingestion.py
    params:
      - make_dataset.test_size
    outs:
      - data/interim

  build_data:
    cmd: src/pipeline/stage1_build_data.py
    deps:
      - ../data/interim/train/train.csv
      - ../data/interim/test/test.csv
      - src/pipeline/stage1_build_data.py
    params:
      - data.drop_columns
    outs:
      - data/processed
  
  build_model:
    cmd: src/pipeline/stage2_build_model.py
    deps:
      - data/processed/train/train.csv
      - data/processed/test/test.csv
      - src/pipeline/stage2_build_model.py
      - src/models/train_model.py
    params:
      - model.experiment_name
      - model.sub_model
      - model.model_name
      - model.metrics
      - model.model_args_name
      - model_params
    outs:
      - models/

  model_evaluator:
    cmd: src/pipeline/stage3_model_evaluator.py
    deps:
      - data/processed/test/test.csv
      - src/pipeline/stage3_model_evaluator.py
      - models/
      - src/models/train_model.py
    params:
      - model.experiment_name
      - model.sub_model
      - model.model_name
      - model.metrics
      - model_params
