# this file will be used to store the model parameters
make_dataset:
  test_size: 0.2

data:
  target_col: "Churn"
  drop_columns:
    - customerID
    - TotalCharges

model:
  experiment_name: "xxx"
  sub_model: ensemble
  model_name: RandomForestClassifier
  metrics:
    - accuracy_score
    - precision_score
    - recall_score

  

