# this file will be used to store the model parameters
make_dataset:
  test_size: 0.1

data:
  target_col: "Churn"
  drop_columns:
    - customerID
    - TotalCharges

model:
  experiment_name: "xxx"
  sub_model: ensemble
  model_name: RandomForestClassifier
  metrics:
    - accuracy_score
    - precision_score
    - recall_score
  model_args_name: random_forest_params
    
model_params:
  random_forest_params:
    n_estimators: 10
    criterion: gini
    max_depth: 3 
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: sqrt
  
  LogisticRegression:
    penalty: l2

  

