#  this file will be used to store the directories

data_directory:
  root_dir: data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
  interim_train: data/interim/train/train.csv
  interim_test: ../data/interim/test/test.csv
  processed_train: data/processed/train/train.csv
  processed_test: data/processed/test/test.csv

artifacts:
  encoder: artifacts/encoder.pkl
  scalar: artifacts/scalar.pkl
  col_names_to_save: artifacts/col_names.json
  target_encoder_dir: artifacts/target_encoder.pkl
  parent_run_dir: artifacts/experiment_params.json

model:
  root_dir: models
  saved_model: models
  
dags_hub: 
  repo_owner: goldirana1111
  repo_name: telco_customer_churn
  tracking_ui: https://dagshub.com/goldirana1111/telco_customer_churn.mlflow

